#! /bin/bash

echo "Enter the field numbers to print (e.g., 1 3 5):"
read -a fields

#echo $fields
#echo ${fields[@]}

all=$(IFS=,;echo "${fields[*]}")
#echo $all
awk -F: -v f="$all" '{ split(f, fsplit, ",") ; for (i in fsplit) print $fsplit[i]}'  asem/test
